### ISSUE TITLE
The repository is excluded 

### ISSUE THREAD

**Issue by SANJAY-NT** [open-for-everyone/hacktoberfest2021#1220]
All contributions made to this repositories are marked as excluded in my profile what should I do.

**Comment by keshavsingh3197** [comment]
You can make more other pull request they only count valid four in this month.


I don't know it is excluded or not but 
I have recommended in readme.md file that don't commit or pull in this repo.  I have mentioned other repo in readme.md file or or at the bottom of this repo.
