### ISSUE TITLE
Feature: Billing System using Python

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [open-for-everyone/hacktoberfest2021#1313]
I want to contribute this project using under hacktoberfest2021. Please assign me this Issue.

**Comment by lovishprabhakar** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by Sulagna-Dutta-Roy** [comment]
They assigned it to me.

**Comment by lovishprabhakar** [comment]
Oh, ok @Sulagna-Dutta-Roy. I thought multiple people could work on an issue, isn't that the case here?

**Comment by Sulagna-Dutta-Roy** [comment]
I guess no 🤔. Not sure
