### ISSUE TITLE
Count Sort Algorithm in C++

### ISSUE THREAD

**Issue by m-code12** [open-for-everyone/hacktoberfest2021#1553]
@keshavsingh4522 Can I work on this?

**Comment by ghost** [comment]
can you assing me this task? i want to work on this.

**Comment by nimishh7** [comment]
Can i work on this issue in c++ ?

**Comment by sonal019** [comment]
Can you assign me this task?

**Comment by losermyluckwithyou007** [comment]
Please Assign me this task .

**Comment by themonikanayak** [comment]
I would like to work on this issue. Please assign this to me.
