### ISSUE TITLE
Game: Guess the number using python

### ISSUE THREAD

**Issue by lovishprabhakar** [open-for-everyone/hacktoberfest2021#1581]
Hi @keshavsingh4522 sir I would like to add a game called guessing the number using python(under hacktoberfest).

A random two digit number will be generated and the user will be asked to guessing a number by giving input. In case the user gets it wrong, they will be asked to input a smaller/greater number depending upon the previous input. If they get it right, a message will be displayed saying the same.

The user will also be told the number of guesses made when they guess the right number.

Kindly allow me to work on this issue under Hacktoberfest 2021.

**Comment by ssurbhi09** [comment]
I can also do that can you assign me?

**Comment by ssurbhi09** [comment]
Can you assign me?

**Comment by lovishprabhakar** [comment]
@keshavsingh4522 sir I have added the game and made a PR #1723. Kindly review and merge it.

**Comment by lovishprabhakar** [comment]
@keshavsingh4522 sir kindly assign this issue to me and check the PR #1723
