### ISSUE TITLE
Feature: Adding - Design Circular Queue in Java

### ISSUE THREAD

**Issue by Ratna04priya** [open-for-everyone/hacktoberfest2021#319]
### Is your feature request related to a problem? Please describe.
PR: #321 
Feature - Adding - Design Circular Queue in Java

Problem Description- 
Design your implementation of the circular queue. The circular queue is a linear data structure in which the operations are performed based on FIFO (First In First Out) principle and the last position is connected back to the first position to make a circle. It is also called "Ring Buffer".

One of the benefits of the circular queue is that we can make use of the spaces in front of the queue. In a normal queue, once the queue becomes full, we cannot insert the next element even if there is a space in 
### Describe alternatives you've considered

Solution- 
Making the functions from scratch to insert, update and delete from queue

**Comment by keshavsingh3197** [comment]
#321 merged.
