### ISSUE TITLE
 Lowest Common Ancestor of Deepest Leaves

### ISSUE THREAD

**Issue by rajbir21-droid** [open-for-everyone/hacktoberfest2021#376]
### Is your feature request related to a problem? Please describe.

Given the root of a binary tree, return the lowest common ancestor of its deepest leaves.

### Describe the solution you'd like

Using the pair<> container of STL  library in c++, I will keep the track of the node with their respective levels and the node with the deepest level will be the answer.

### Describe alternatives you've considered

It can also be done using hashmap but using pair the code becomes more clear and concise.

**Comment by tanvideshmukh29** [comment]
Hi! I would love to work on this issue? can you please assign it to me?
