### ISSUE TITLE
Dijkstra algorithm for shortest path in weighted graph

### ISSUE THREAD

**Issue by TheDesTrucToRR** [open-for-everyone/hacktoberfest2021#458]
Used to find the shortest path between two distinct point in a weighted network in python.

**Comment by TheDesTrucToRR** [comment]
@keshavsingh4522 I want to work on it. Please assign it to me.
Thanks

**Comment by tanvideshmukh29** [comment]
Hi! I would love to work on this issue? can you please assign it to me?

**Comment by TheDesTrucToRR** [comment]
@tanvideshmukh29 Sorry I m working on this issue....please find another one.

**Comment by dinshajaiswal** [comment]
I would like to work on this issue. Could you please assign it to me @keshavsingh4522
