### ISSUE TITLE
Feature:  Array operations

### ISSUE THREAD

**Issue by SANJAY-NT** [open-for-everyone/hacktoberfest2021#762]
### Is your feature request related to a problem? Please describe.

To implement the array operations in python using list

### Describe the solution you'd like

List can be used as a array in python instead of numpy for basic operation , So i would like to demonstrate its implementation

### Describe alternatives you've considered

Instead of numpy using basic data structure in python

Note: consider under Hacktoberfest 21

**Comment by PAARTH2608** [comment]
Can i work on this issue?

**Comment by creater-shikha** [comment]
can i contribute in this

**Comment by SANJAY-NT** [comment]
@keshavsingh4522  Can assign the issue.

**Comment by SANJAY-NT** [comment]
I have updated a pull request #1212 can you review and merge the PR for Hacktoberfest 21.
@keshavsingh4522
