### ISSUE TITLE
Detection of linkedlist in java 

### ISSUE THREAD

**Issue by KhushiChaudhary744** [open-for-everyone/hacktoberfest2021#874]
Hey, i am a participant of hacktoberfest and would love to contribute.

**Comment by chehak123** [comment]
Can I work on it?

**Comment by keshavsingh4522** [comment]
> Can I work on it?

Of course. But after completion tell me here with pull request url or number

**Comment by keshavsingh3197** [comment]
> Can I work on it?

Ofcourse. But notify me by commenting in discussion box with pull request number or url
